---
- name: include variable overrides
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "vars/{{ ansible_distribution }}.yml"
        - "vars/{{ ansible_os_family }}.yml"
      skip: true

- name: install package requirements for debian derivatives
  apt:
    name: xz-utils
    state: present
  when: (ansible_os_family | lower) == 'debian'

- name: install vagrant packages for debian derivatives
  apt:
    deb: xz-utils
    state: "{{ vagrant_packages_state }}"
  when: (ansible_os_family | lower) == 'debian'

- name: install vagrant packages for redhat derivatives
  yum:
    name: "{{ vagrant_packages | default(vagrant_packages_default) }}"
    state: "{{ vagrant_packages_state }}"
