---
- block:

    - name: install package requirements for debian derivatives
      apt:
        name: xz-utils
        state: present
      when: (ansible_os_family | lower) == 'debian'

    - name: install default packages for debian derivatives
      apt:
        deb: "{{ vagrant_packages | default(vagrant_packages_deb_default) }}"
        state: "{{ vagrant_packages_state }}"

  when: (ansible_os_family | lower) == 'debian'

- name: install vagrant packages for redhat derivatives
  yum:
    name: "{{ vagrant_packages | default(vagrant_packages_rpm_default) }}"
    state: "{{ vagrant_packages_state }}"
  when: (ansible_os_family | lower) == 'redhat'
